# Generated by Django 5.2.12 on 2026-03-24 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('granos', 'Granos y cereales'), ('aceites', 'Aceites'), ('aseo', 'Aseo'), ('lacteos', 'Lácteos'), ('otros', 'Otros')], max_length=50)),
                ('unit', models.CharField(choices=[('u', 'Unidades'), ('kg', 'Kilogramos'), ('l', 'Litros'), ('g', 'Gramos')], max_length=10)),
                ('current_stock', models.IntegerField(default=0)),
                ('safety_stock', models.IntegerField(default=0)),
                ('lead_time_days', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField()),
                ('sale_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.product')),
            ],
        ),
    ]
